cc_library(
  name="serialization",
  hdrs=["serialization.hpp", "serialization_fwd.hpp"],
  include_prefix="sde",
  deps=[
    "//core/serialization/archive",
    "//core/serialization/stream",
    "//core/serialization/primitives",
    "//core/serialization/object",
  ],
  visibility=["//visibility:public"]
)
